### PR TITLE
export 'ValueType'

### PR DESCRIPTION
**Pull request by evilfant**
To be able to add custom value types
For example
```
import { ValueType } from 'behave-graph`

type Vector3 = { x: number, y: number, z: number };

valuesRegistry.register(new ValueType('vector3', () => ({ x: 0, y: 0, z: 0 }), (text: any) => text, (value: Vector3) => value));
```

### CODE REVIEW

**Review by beeglebug — APPROVED** [review]
Looks good, thanks!

**Comment by bhouston** [comment]
Did the custom types work otherwise @evilfant?  I designed it for extensibility but I never actually did try it out on a complex type.

**Comment by bhouston** [comment]
I also wonder if we should have a repo with Vector3 nodes that we could include?  Like ```@behave-graph/vector3``` or something like that.  I could put the current node set into ```@behave-graph/core```?

**Comment by beeglebug** [comment]
a separate repo is probably overkill, if the exports are set up right we can put a few sub sets of common nodes in this repo, let people import as they wish, and let tree shaking in userland sort it out

something like 'import { registerVector3Nodes } from "behave-graph/vector3"` would probably work

**Comment by beeglebug** [comment]
we could still go down the separate repo route for nodes which are more tightly coupled to another library or environment, such as `@behave-graph/three` for example, where peer dependencies become an issue

**Comment by evilfant** [comment]
[bhouston](https://github.com/bhouston), with `ValueType` export it works. I tried it with custom Vector3.
Graph node looks like
```json
{
  "type": "logic/vector3Constant",
  "id": "3",
  "inputs": {
      "a": { "value": {"x": 5, "y": 6, "z": 7} }
  }
}
```
(`logic/vector3Constant` is a custom node)
All other things extend well
There are some problems with typings (I described [them here](https://github.com/bhouston/behave-graph/pull/68))

**Pull request merged**
